### ISSUE TITLE
Water draining bug

### ISSUE THREAD

**Issue by Strangeys** [OvercastCommunity/Mapmaker#20]
Water is acting very weird. Essentially I can place water and have it flow like it would in vanilla, but getting rid of the source or cutting water away from the source has weird effects that require odd block updates for it to continue draining and at times you'll need to just do //drain or place a block in every single place the water stream went.

Example and how to reproduce:
1) Place water and let it flow
![2021-07-09_04 02 48](https://user-images.githubusercontent.com/4961627/125045568-22820180-e06b-11eb-89e7-3ace47daca2b.png)

2) Destroy the source (this can also be any part of the flowing contents). This screenshot is taken seconds after the block had been placed and it is not draining.
![2021-07-09_04 03 00](https://user-images.githubusercontent.com/4961627/125045586-2746b580-e06b-11eb-9d52-3630705ef0da.png)

3) Break the block that I just killed the source with. This screenshot is also taken seconds after destroying the block and the water is still not draining.
![2021-07-09_04 03 11](https://user-images.githubusercontent.com/4961627/125045591-2877e280-e06b-11eb-97e3-391291df1e7b.png)

If possible, having a way for us to toggle when we want water physics updates to occur would be nice although that could be a separate issue if needed.

**Comment by applenick** [comment]
Fixed! Water should flow correctly now, but have not added a toggle. Will include that once a map world settings menu is added.
